# Generated by Django 6.1.1 on 2026-09-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("000", "000 - Generalidades e Informação"),
                    ("100", "100 - Filosofia e Psicologia"),
                    ("200", "200 - Religião e Teologia"),
                    ("300", "300 - Ciências Sociais e Direito"),
                    ("400", "400 - Linguística e Idiomas"),
                    ("500", "500 - Ciências Puras (Exatas e Naturais)"),
                    ("600", "600 - Ciências Aplicadas (Tecnologia)"),
                    ("700", "700 - Artes e Recreação"),
                    ("800", "800 - Literatura"),
                    ("900", "900 - História e Geografia"),
                ],
                default=0,
                max_length=3,
            ),
            preserve_default=False,
        ),
    ]
