# Generated by Django 6.1.1 on 2026-09-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_produto_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("INF", "Informática"),
                    ("ELE", "Eletrônicos"),
                    ("ESC", "Material de Escritório"),
                    ("LIM", "Material de Limpeza"),
                    ("FER", "Ferramentas"),
                    ("EPI", "Equipamentos de Proteção"),
                    ("MOV", "Móveis"),
                    ("OUT", "Outros"),
                ],
                max_length=3,
            ),
        ),
    ]
